version: 1

models:
  - name: mart_all_tracks_versions
    description: ""
    columns:
      - name: album_id
        data_type: text
        description: ""

      - name: album_url
        data_type: text
        description: ""

      - name: album_uri
        data_type: text
        description: ""

      - name: album_type
        data_type: text
        description: ""

      - name: album_name
        data_type: text
        description: ""

      - name: album_total_tracks
        data_type: integer
        description: ""

      - name: album_release_date
        data_type: date
        description: ""

      - name: album_image_url
        data_type: text
        description: ""

      - name: album_popularity
        data_type: integer
        description: ""

      - name: track_id
        data_type: text
        description: ""

      - name: track_url
        data_type: text
        description: ""

      - name: track_uri
        data_type: text
        description: ""

      - name: track_disk_number
        data_type: bigint
        description: ""

      - name: track_duration_seconds
        data_type: bigint
        description: ""

      - name: track_name
        data_type: text
        description: ""

      - name: track_number
        data_type: bigint
        description: ""

      - name: track_popularity
        data_type: integer
        description: ""

      - name: track_irsc
        data_type: character varying
        description: ""

      - name: track_version_rank
        data_type: bigint
        description: ""

  - name: mart_all_tracks
    description: ""
    columns:
      - name: album_id
        data_type: text
        description: ""

      - name: album_url
        data_type: text
        description: ""

      - name: album_uri
        data_type: text
        description: ""

      - name: album_type
        data_type: text
        description: ""

      - name: album_name
        data_type: text
        description: ""

      - name: album_total_tracks
        data_type: integer
        description: ""

      - name: album_release_date
        data_type: date
        description: ""

      - name: album_image_url
        data_type: text
        description: ""

      - name: album_popularity
        data_type: integer
        description: ""

      - name: track_id
        data_type: text
        description: ""

      - name: track_url
        data_type: text
        description: ""

      - name: track_uri
        data_type: text
        description: ""

      - name: track_disk_number
        data_type: bigint
        description: ""

      - name: track_duration_seconds
        data_type: bigint
        description: ""

      - name: track_name
        data_type: text
        description: ""

      - name: track_number
        data_type: bigint
        description: ""

      - name: track_popularity
        data_type: integer
        description: ""

      - name: track_irsc
        data_type: character varying
        description: ""

  - name: mart_setlist_history
    description: ""
    columns:
      - name: event_set_song_id
        data_type: text
        description: ""

      - name: event_id
        data_type: text
        description: ""

      - name: event_date
        data_type: date
        description: ""

      - name: event_info
        data_type: text
        description: ""

      - name: event_url
        data_type: text
        description: ""

      - name: event_tour_id
        data_type: text
        description: ""

      - name: event_tour
        data_type: text
        description: ""

      - name: venue_id
        data_type: text
        description: ""

      - name: venue_name
        data_type: text
        description: ""

      - name: venue_city
        data_type: text
        description: ""

      - name: venue_state_code
        data_type: text
        description: ""

      - name: venue_country_code
        data_type: text
        description: ""

      - name: venue_latitude
        data_type: double precision
        description: ""

      - name: venue_longitude
        data_type: double precision
        description: ""

      - name: set_index
        data_type: bigint
        description: ""

      - name: encore_index
        data_type: integer
        description: ""

      - name: encore_flag
        data_type: boolean
        description: ""

      - name: song_index
        data_type: bigint
        description: ""

      - name: song_position_in_set_index
        data_type: bigint
        description: ""

      - name: song_name
        data_type: text
        description: ""

      - name: song_info
        data_type: text
        description: ""

      - name: song_cover_flag
        data_type: boolean
        description: ""

      - name: song_cover_artist_mbid
        data_type: text
        description: ""

      - name: song_cover_artist_name
        data_type: text
        description: ""

      - name: song_with_flag
        data_type: boolean
        description: ""

      - name: song_with_artist_mbid
        data_type: text
        description: ""

      - name: song_with_artist_name
        data_type: text
        description: ""

