[project]
name = "setkit"
version = "0.1.0"
description = "On the Setlist Analytics SDK"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "pandas>=2.2",
  "plotnine>=0.14"
]

[project.optional-dependencies]
dev = ["ipykernel", "ruff", "pytest"]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
